### PR TITLE
Change username anaconda-server to AER-admin

### PR DESCRIPTION
**Pull request by kerrywatson1**
@mrduane you or @bkreider MUST REVIEW AND APPROVE THIS PR. I believe I changed all instances of username anaconda-server to AER-admin, but there are many references to anaconda-server in paths and commands. Please make sure I did not change a path or command!!!

Thanks guys.

### CODE REVIEW

**Comment by kerrywatson1** [comment]
@electronwill I'd be grateful if you checked this, as well. Thanks!

**Comment by electronwill** [comment]
OK, I searched the file for all instances of the username (now "aer_admin"), "anaconda-server", and "binstar", and I believe they are all correct and consistent. Changing the remaining instances of "anaconda-server" and "binstar" will require the devs to make code changes to the script names, channel names, hard-coded directory names, and so on.

**Comment by kerrywatson1** [comment]
A great idea whose time has not come yet. Closing!

**Comment by bkreider** [comment]
Sorry, I was out all week.

**Pull request closed without merging**
