### PR TITLE
note that AEN Compute nodes need X installed

### PR DESCRIPTION
**Pull request by electronwill**
note that AEN Compute nodes need X installed

### CODE REVIEW

**Comment by damianavila** [comment]
I think it is OK, but I defer to @trentoliphant the last word if they want something more here.

**Comment by kerrywatson1** [comment]
We can always add more info later, so if this meets the original intent please merge and close. Thx!

**Comment by electronwill** [comment]
Sounds good. @trentoliphant if there's more info you'd like us to add, please reply here or make a new issue in this repo and @-mention us.

**Comment by electronwill** [comment]
Change is deployed and visible at http://runbooks.readthedocs.io/en/latest/AnacondaEnterpriseNotebooks.html .

**Pull request merged**
