### PR TITLE
Anaconda-server to aer_admin

### PR DESCRIPTION
**Pull request by kerrywatson1**
Separate branch for this edit in case somebody decides to back out all the default admin user changes.

### CODE REVIEW

**Comment by kerrywatson1** [comment]
@electronwill please check!
@mrduane or @bkreider please review.

**Comment by electronwill** [comment]
I changed the home directory names from "anaconda-server" to "aer_admin". I also noticed the file used smart quotes, and since Sphinx omits these without warnings or errors in our main system, I went ahead and changed them to regular quotes. Then I searched for all instances in the file of each of the three terms "anaconda-server", "aer_admin", and "binstar", and they all looked correct to me.

**Comment by mrduane** [comment]
@trentoliphant any thoughts on this? LGTM.

**Comment by kerrywatson1** [comment]
You can still continue to use the default you prefer; this just
standardizes to the rest of the docs and makes it easier for the reader to
grasp what we are referring to. When many things are called Anaconda-server
(besides being outdated) it causes more cognitive load to have to mentally
sort them out on each occurrence. We do want people to be able to install
this themselves eventually so this gets us one step closer.

Just my $0.02.

**Comment by kerrywatson1** [comment]
We've decided to change no default usernames in the current version of the docs, so closing this issue.

**Pull request closed without merging**
