### PR TITLE
AEN: ports other than server are configurable

### PR DESCRIPTION
**Pull request by electronwill**
AEN: ports other than server are configurable

### CODE REVIEW

**Comment by electronwill** [comment]
From "AE-Notebooks" Flowdock channel:
Bradley: I'm not sure why this says they are not configurable.  I'm pretty sure the only port that isn't configurable is the wk-server port that is behind nginx.
Damian: Probably a doc error, and there is missing docs about how to configure some of them as well (there are open issues about that). But yes, they are configurable except the one you mentioned, IIRC.
Bradley: That chart came right out of the implementation runbook, so it just needs to be fixed now.

@bkreider and @damianavila please review-- is this change correct?

**Comment by electronwill** [comment]
Confirmed by @pandres . If anyone sees any necessary further changes, please let me know.

**Comment by electronwill** [comment]
Published and checked at http://runbooks.readthedocs.io/en/latest/AnacondaEnterpriseNotebooks.html .

**Comment by damianavila** [comment]
Just one clarification... the wk-server port not configurable is the internal one behind the nginx, and it is port 5000 on localhost, but the nginx port 80 is configurable AFAIK.

**Comment by electronwill** [comment]
Thank you. Do you think this information needs to be added to the runbook?

**Comment by damianavila** [comment]
>Thank you. Do you think this information needs to be added to the runbook?

Maybe a note with the clarification is not harmful...

**Comment by electronwill** [comment]
The runbooks have now been deprecated and this is fixed in https://github.com/ContinuumIO/aen-docs/blob/master/docs/install/installation.rst , so no further changes are necessary.

**Pull request merged**
